package sh.vork.relay.lib.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * The encrypted form response submitted by the user's browser.
 *
 * <p>The browser encrypts the user's input client-side (using the same
 * AES-256-GCM key from the URL hash) before POSTing.  The server stores
 * only ciphertext and delivers it to the polling offline container.
 *
 * <ul>
 *   <li>{@code encryptedResponse} – AES-256-GCM ciphertext of the response JSON
 *   <li>{@code nonce}             – fresh 96-bit IV generated by the browser
 *   <li>{@code authTag}           – 128-bit GCM authentication tag
 * </ul>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record RelaySubmission(
        String encryptedResponse,
        String nonce,
        String authTag
) {}
